### PR TITLE
Vertically align the modal dialog close buttons within the header.

### PR DESCRIPTION
**Pull request by iwehrman**
Before: 
before

After:
after

(The `line-height` of the `<h1>` in the header is set to 40 pixels, and there is a default non-zero `top-margin` defined elsewhere.)

### CODE REVIEW

**Comment by iwehrman** [comment]
(Ignore the weird orange `<head>` tag. That's just in my local tree.)

**Comment by iwehrman** [comment]
CC @larz0

**Comment by larz0** [comment]
@iwehrman thanks man that looks so much better now!

**Comment by couzteau** [comment]
looking good. meging

**Pull request merged**
