### PR TITLE
Use _.escape() instead of StringUtils.htmlEscape()

### PR DESCRIPTION
**Pull request by le717**
After a long deprecation phase, `StringUtils.htmlEscape()` has been removed. This extension makes use of this removed API. This PR updates it to use `_.escape()` instead to prevent your extension from breaking. Full details are at adobe/brackets#8960.

-le717

### CODE REVIEW

**Comment by le717** [comment]
@ryanstewart (I don't know who to contact for this) Can you see about merging this or merge it yourself so the extension won't be broken once 1.0 is released?

**Comment by iwehrman** [comment]
Drive-by review: this looks totally fine to me, but I'd rather one of the current Brackets engineers push the merge button. CC @ingorichter @couzteau.

**Comment by ryanstewart** [comment]
@iwehrman you don't trust me?! I can push a merge button as well as anyone! :)

I'll email the team and have someone double check this. Thanks @le717 !

**Comment by iwehrman** [comment]
I trust you implicitly @ryanstewart :) I just meant that _I_ didn't feel comfortable pushing the merge button, and I also wanted to spam some other Brackets engineers in case you were too busy managin' yr products.

**Comment by le717** [comment]
@iwehrman @ryanstewart JSYK, this PR is following the replacement recommendation of the now-removed function. :)

**Comment by redmunds** [comment]
@le717 This looks good. Can you also increment the version number in **package.json** to `"version": "0.1.6"` so we can upload to Extension Manager?

**Comment by le717** [comment]
@redmunds Done.

**Comment by redmunds** [comment]
@le717 Thanks for fixing and then reminding us that it was fixed! Merging.

**Comment by le717** [comment]
@redmunds Follow up on PRs don't usually hurt. I know I'd want people to remind me if I had a PR to be merged and I had not done it. :)

**Comment by redmunds** [comment]
@ryanstewart I can't update this extensions in the Brackets Registry:

update-ewf

I thought I was made an owner of this Adobe Extension, but maybe it was a different one. Looks like @jadbox updated it last.

**Pull request merged**
